### ISSUE TITLE
채널명 중복 허용에 관한 논의

### ISSUE THREAD

**Issue by nureesong** [sds-newbie-longs/longs-backend#75]
채널 삭제시, 해당 채널에 있는 게시글도 모두 삭제 요청을 날려야 하는 문제 때문에
채널 테이블에도 status 컬럼을 만들어 created, deleted로 관리하는 방식으로 변경됐습니다.

그런데, 채널 삭제 후 같은 이름으로 다시 채널을 생성하면 채널명이 unique라서 실패처리가 되는 문제가 있네요.
그렇다면 채널명에 중복을 허용하는 게 맞을지 월요일에 논의해보고 싶어요!

**Comment by seonpilKim** [comment]
역시 꼼꼼한 null👍👍

이런 경우에는 비즈니스 정책(채널 이름은 고유해야 한다.)을 DB level이 아닌 Application level에서 구현하면 될 것 같아요.
- status가 Created인 채널이 있는지 먼저 체크해보고 생성하는 로직으로 변경
- name 컬럼 unique 제약조건 해제
